### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/payment-server#16]
Can we get a license added to this repository? 

I'd assume it would be released under [Apache 2.0](http://www.apache.org/licenses/LICENSE-2.0) like the [Hedera Browser Extension](https://github.com/hashgraph/hedera-browser-extension/blob/master/LICENSE.md)

**Comment by calvinchengx** [comment]
Thanks!  Legal did mention some modifications to that.

Adding it now.

**Comment by calvinchengx** [comment]
Resolved via #5dc2778 #
